### ISSUE TITLE
Project does not build on Windows due to NLS characters in code / no source file encoding specified

### ISSUE THREAD

**Issue by elygre** [AcandoNorway/XmlToRdf#5]
The project does not build on Windows, due to the use of NLS chars in source code. Unless the javac option "-encoding" is specified, the platform default converter is used (http://docs.oracle.com/javase/6/docs/technotes/tools/windows/javac.html).

(Source code based on revision 49798f05eabbac0c71f486a450abeda0e497d6b4)
```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project xmltordf: Compilation failure: Compilation failure:
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[681,23] illegal character: '\u00b8'
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[682,23] illegal character: '\u00a6'
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[689,52] illegal character: '\u00b8'
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[689,77] illegal character: '\u00a6'
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[689,78] illegal start of expression
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[689,79] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[690,13] illegal start of expression
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[690,31] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[690,38] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[690,49] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[690,52] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[690,55] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[690,84] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[690,87] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[691,21] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[696,52] illegal character: '\u00b8'
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[696,77] illegal character: '\u00a6'
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[696,78] illegal start of expression
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[696,79] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[697,13] illegal start of expression
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[697,31] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[697,38] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[697,49] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[697,52] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[697,55] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[697,84] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[697,87] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[698,21] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[703,52] illegal character: '\u00b8'
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[703,77] illegal character: '\u00a6'
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[703,78] illegal start of expression
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[703,79] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[704,13] illegal start of expression
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[704,31] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[704,38] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[704,49] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[704,52] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[704,55] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[704,84] not a statement
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[704,87] ';' expected
[ERROR] /C:/git/XmlToRdf/xmltordf/src/test/java/XmlToRdfTest.java:[705,21] ';' expected
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by hmottestad** [comment]
@elygre Could you try branch 5-encoding?

**Comment by elygre** [comment]
Yes, with that branch it compiles nicely :-).

However, it fails while executing tests:

```
Tests run: 64, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 0.999 sec <<< FAILURE!
specialShallowHandling(XmlToRdfTest)  Time elapsed: 0.006 sec  <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.nio.charset.MalformedInputException: Input length = 1
        at org.apache.jena.atlas.io.IO.exception(IO.java:216)
        at org.apache.jena.atlas.io.CharStreamBuffered$SourceReader.fill(CharStreamBuffered.java:77)
        at org.apache.jena.atlas.io.CharStreamBuffered.fillArray(CharStreamBuffered.java:154)
        at org.apache.jena.atlas.io.CharStreamBuffered.advance(CharStreamBuffered.java:137)
        at org.apache.jena.atlas.io.PeekReader.advanceAndSet(PeekReader.java:235)
        at org.apache.jena.atlas.io.PeekReader.init(PeekReader.java:229)
        at org.apache.jena.atlas.io.PeekReader.peekChar(PeekReader.java:151)
        at org.apache.jena.atlas.io.PeekReader.makeUTF8(PeekReader.java:92)
        at org.apache.jena.riot.tokens.TokenizerFactory.makeTokenizerUTF8(TokenizerFactory.java:48)
        at org.apache.jena.riot.lang.RiotParsers.createParser(RiotParsers.java:61)
        at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:171)
        at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:861)
        at org.apache.jena.riot.RDFDataMgr.parse(RDFDataMgr.java:667)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:212)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:145)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:134)
        at org.apache.jena.riot.adapters.AdapterFileManager.readModelWorker(AdapterFileManager.java:282)
        at org.apache.jena.util.FileManager.readModel(FileManager.java:341)
        at org.apache.jena.util.FileManager.readModel(FileManager.java:325)
        at XmlToRdfTest.testAdvancedStream(XmlToRdfTest.java:1333)
        at XmlToRdfTest.specialShallowHandling(XmlToRdfTest.java:685)
        ... (stacktrace from maven and junit ommitted)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.Reader.read(Reader.java:140)
        ... 51 more
```

This is probably a different problem, though, caused by an encoding problem in a test file.

**Comment by hmottestad** [comment]
Seems like an encoding problem with the string output module. I've set encoding to UTF8. Could you pull and test again @elygre ?

**Comment by elygre** [comment]
Still failing, though differently. How about waiting until after the vacation, and fixing it then?

```
Tests run: 64, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.082 sec <<< FAILURE!
specialShallowHandling(XmlToRdfTest)  Time elapsed: 0.051 sec  <<< FAILURE!
junit.framework.ComparisonFailure: Not isomorphic for object method with sesame repository. expected:<...04/02/skos/core
#> .
[@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .

<http://example.com/L°vtrµr>
        a              skos:Concept ;
        rdf:nodeID     "L°vtrµr" ;
        skos:narrower  <http://example.com/Vanlig-bj°rk> .

[ a                  rdf:RDF ;
  xmlToRdf:hasChild  <http://example.com/L°vtrµr> , <http://example.com/Vanlig-bj°rk>
] .

<http://example.com/Vanlig-bj°rk>
        a             skos:Concept ;
        rdf:nodeID    "Vanlig-bj°rk" ;
        skos:broader  <http://example.com/L°vtrµr]> .
> but was:<...04/02/skos/core#> .
[
[ a                  rdf:RDF ;
  xmlToRdf:hasChild  <http://example.com/Vanlig-bj?rk> , <http://example.com/L?vtr?r>
] .

<http://example.com/Vanlig-bj?rk>
        a             skos:Concept ;
        rdf:nodeID    "Vanlig-bj?rk" ;
        skos:broader  <http://example.com/L?vtr?r> .

<http://example.com/L?vtr?r>
        a              skos:Concept ;
        rdf:nodeID     "L?vtr?r" ;
        skos:narrower  <http://example.com/Vanlig-bj?rk]> .
>
```

**Comment by hmottestad** [comment]
At this point I don't know what could be causing this. Everything should be using UTF8 now and I'm not sure where it is defaulting back to the platform encoding. Things would be so much simpler if Windows started using UTF8 :D 

I will have to look at it after my holiday. Thanks for the patience @elygre , I'm sure I'll get to the bottom of it when I get back. In the mean time you can use "maven install -DskipTests" if you want to keep playing with the library and aren't going to use any UTF8 specific characters in your test files.
